// Auto-generated by Supabase CLI — do not edit manually.
// Run: pnpm supabase gen types typescript --project-id <your-project-id> > types/database.types.ts
//
// This file is intentionally empty until the first schema migration is applied (SB-002).

export type Database = Record<string, never>;
